_target_: navsim.agents.transfuser_oneframe_str.Tran_1StrAgent.TranDPagent
_convert_: 'all'

config:
  _target_: navsim.agents.transfuser_oneframe_str.TranDPconfig.TranDPConfig
  _convert_: 'all'

  trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    time_horizon: 4
    interval_length: 0.5

checkpoint_path: /cephfs/zhanjh/exp/training_oneframe_str_agent/2024.05.27.16.58.54/lightning_logs/temp45.ckpt
lr: 1e-4
